### ISSUE TITLE
Error when running generator

### ISSUE THREAD

**Issue by MelanieMenard** [yeoman/generator-backbone#395] opened 2016-05-04 16:37 UTC
Hello,

I run this command inside the directory where I want to scaffold my app (capsule is my app name)

`yo backbone capsule --template-framework=handlebars`

The following error happens

```
undefined
Out of the box I include HTML5 Boilerplate, jQuery and Backbone.js.
? What more would you like? (Press <space> to select)Twitter Bootstrap for Sass
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/generator-backbone/generators/app/templates/app/scripts'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:794:18)
    at Function.sync (/usr/local/lib/node_modules/generator-backbone/node_modules/mkdirp/index.js:71:13)
    at yeoman.generators.Base.extend.writing.setupEnv (/usr/local/lib/node_modules/generator-backbone/generators/app/index.js:305:14)
    at /usr/local/lib/node_modules/generator-backbone/node_modules/yeoman-generator/lib/base.js:430:16
    at processImmediate [as _immediateCallback] (timers.js:383:17)
MelanieMenards-MacBook-Pro:capsule melaniemenard$ 
```

Please note `undefined` appears whether or not I specify the template, and the JS error happens whether I select twitter bootstrap or no extra at all.

I've never used Yeoman before so following tutorials to the letter. Any advice much appreciated.

Many thanks.

Melanie.

**Comment by Htbaa** [comment] 2016-07-13 12:30
Happens for me as well (also never used Yeoman before, though it would be a good time to start...).

For me this happens on Ubuntu 16.04 running in a Vagrant managed VirtualBox VM.

**Comment by bufface** [comment] 2016-07-15 17:21
Same error (Ubuntu 16.04):

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/generator-backbone/generators/app/templates/app/scripts'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:922:18)
    at Function.sync (/usr/lib/node_modules/generator-backbone/node_modules/mkdirp/index.js:71:13)
    at yeoman.generators.Base.extend.writing.setupEnv (/usr/lib/node_modules/generator-backbone/generators/app/index.js:305:14)
    at /usr/lib/node_modules/generator-backbone/node_modules/yeoman-generator/lib/base.js:430:16
    at runCallback (timers.js:566:20)
    at tryOnImmediate (timers.js:546:5)
    at processImmediate [as _immediateCallback] (timers.js:525:5)
```

**Comment by bufface** [comment] 2016-08-10 15:02
Hey @MelanieMenard could you solve this? I still have same behavior.

**Comment by h4ck3rm1k3** [comment] 2016-08-27 09:47
I am having this as well.

**Comment by h4ck3rm1k3** [comment] 2016-08-27 09:50
installing the generator-backbone locally resolved this, it was installed globally.

**Comment by bufface** [comment] 2016-08-27 14:23
@h4ck3rm1k3 You're right. Thanks

**Comment by eddiemonge** [comment] 2016-08-29 18:53
duplicate of #388

**Closed as completed by eddiemonge** 2016-08-29 18:53 UTC

**Comment by welt13** [comment] 2017-10-28 12:23
I have a Mac and I have been able to install the backbone generator well. I have installed everything in a global way without sudo and it has worked.
